/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nashtechglobal;

import com.nashtechglobal.slf4j.testdebug.Debug01;
import com.nashtechglobal.slf4j.testdebug.Debug02;
import com.nashtechglobal.slf4j.testinfo.Info01;

public class LoggingDemo {

	public static void main(String[] args) {
		Debug01.writeLog();
		Debug02.writeLog();
		Info01.writeLog();
	}
}
